# DS605: Fundamentals of Machine Learning
## Part A - Vectorized Programming with NumPy
### Task 1 - Arrays, Statistics, and Indexing
 

● Generate Array A with 100 random integers. Set a random seed for reproducibility.

In [1]:
import numpy as np
np.random.seed(42)

array_a = np.random.randint(1, 101, size=100)

print("Array A:")
print(array_a)

Array A:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


### Basic Statistics of Array A

Use NumPy functions to find min, max, median, mean, and standard deviation of Array A.

In [2]:
print("Minimum:", np.min(array_a))
print("Maximum:", np.max(array_a))
print("Median:", np.median(array_a))
print("Mean:", np.mean(array_a))
print("Standard Deviation:", np.std(array_a))

Minimum: 2
Maximum: 100
Median: 54.0
Mean: 51.54
Standard Deviation: 29.278463074417004


### Generate Array B using `np.arange()`



In [3]:
array_b = np.arange(1, 101)

print("Array B:")
print(array_b)

print("Number of values:", array_b.size)

Array B:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Number of values: 100


### Using `np.zeros()` and `np.ones()`



In [4]:
zeros_array = np.zeros((3, 4))
ones_array = np.ones((2, 5))

print("Zeros Array:")
print(zeros_array)
print("Shape:", zeros_array.shape)
print("Data Type:", zeros_array.dtype)

print("\nOnes Array:")
print(ones_array)
print("Shape:", ones_array.shape)
print("Data Type:", ones_array.dtype)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Data Type: float64

Ones Array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)
Data Type: float64


### Using `np.linspace()`



In [5]:
linspace_array = np.linspace(0, 10, 5)

print("Linspace Array:")
print(linspace_array)

Linspace Array:
[ 0.   2.5  5.   7.5 10. ]


### ● Create one 2D and one 3D array. Show shape, ndim, indexing, rows, columns, and slicing.

In [6]:
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("2D Array:")
print(array_2d)

print("\nShape:", array_2d.shape)
print("Number of Dimensions:", array_2d.ndim)

2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Shape: (3, 3)
Number of Dimensions: 2


In [7]:
print("Element at first row, second column(indexing):", array_2d[0, 1])
print("First Row:")
print(array_2d[0])
print("Second Column:")
print(array_2d[:, 1])
print("First two rows and first two columns:")
print(array_2d[0:2, 0:2])

Element at first row, second column(indexing): 20
First Row:
[10 20 30]
Second Column:
[20 50 80]
First two rows and first two columns:
[[10 20]
 [40 50]]


In [8]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(array_3d)

print("\nShape:", array_3d.shape)
print("Number of Dimensions:", array_3d.ndim)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)
Number of Dimensions: 3


In [9]:
print("Selected Element:", array_3d[0, 1, 2])
print("First Block:")
print(array_3d[0])
print("First row of first block:")
print(array_3d[0, 0])
print("Second column of first block:")
print(array_3d[0, :, 1])
print("First two columns from all blocks:")
print(array_3d[:, :, 0:2])

Selected Element: 6
First Block:
[[1 2 3]
 [4 5 6]]
First row of first block:
[1 2 3]
Second column of first block:
[2 5]
First two columns from all blocks:
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


### Reshape and Flatten an Array

In [10]:
original_array = np.arange(1, 13)

print("Original 1D Array:")
print(original_array)

matrix = original_array.reshape(3, 4)

print("\nReshaped Matrix:")
print(matrix)

flattened_array = matrix.flatten()

print("\nFlattened Array:")
print(flattened_array)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Task 2 - Vectorized Arithmetic and Linear Algebra


### 1. Create Two Matrices

In [11]:
matrix_a = np.array([
    [1, 2],
    [3, 4]
])

matrix_b = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


### 2. Matrix Addition

In [12]:
addition = matrix_a + matrix_b

print("Matrix Addition:")
print(addition)

Matrix Addition:
[[ 6  8]
 [10 12]]


### 3. Element-wise Multiplication

Element-wise multiplication multiplies corresponding elements of the two matrices.

In [14]:
element_multiplication = matrix_a * matrix_b

print("Element-wise Multiplication:")
print(element_multiplication)

Element-wise Multiplication:
[[ 5 12]
 [21 32]]


### 4. Matrix Multiplication
